POST http://localhost:8080/api/orders
Content-Type: application/json

{
  "customerId": 1233,
  "deliveryAddress": "Hyderabad",
  "item": {
    "code": "P100",
    "name": "Product 1",
    "price": "34.0",
    "quantity": 1
  }
}

###

